name: CI Pipeline

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SLACK_CHANNEL: 'Laxmi Prasanna'
      AWS_REGION: eu-west-1
      AWS_PROFILE: dev
          
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Extract branch name
        id: extract_branch
        run: echo "BRANCH_NAME=$(echo ${{ github.ref }} | sed 's/refs\/heads\///')" >> $GITHUB_ENV
    
      - name: Set Environment Stage
        run: |
          BRANCH=${{ github.ref.split('/')[2] }}
          if [ "$BRANCH" == "test" ]; then
            echo "AWS_DEPLOY_STAGE_ENVIRONMENT=test" >> $GITHUB_ENV
          elif [ "$BRANCH" == "develop" ]; then
            echo "AWS_DEPLOY_STAGE_ENVIRONMENT=dev" >> $GITHUB_ENV
          elif [ "$BRANCH" == "staging" ]; then
            echo "AWS_DEPLOY_STAGE_ENVIRONMENT=staging" >> $GITHUB_ENV
          elif [ "$BRANCH" == "master" ]; then
            echo "AWS_DEPLOY_STAGE_ENVIRONMENT=root" >> $GITHUB_ENV
          else
            echo "AWS_DEPLOY_STAGE_ENVIRONMENT=unknown" >> $GITHUB_ENV
          fi    
      - name: Prepare Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y dos2unix
          git submodule update --init --recursive
          dos2unix install.sh
          chmod +x install.sh
          bash install.sh


      - name: Send Notification to Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          # SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: '#FFFF00'
          SLACK_TITLE: "Build starting for platform-manual-services"
          SLACK_MESSAGE: "Build ${{ github.run_number }} for platform-manual-services is STARTING. :rocket: View Run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          SLACK_CHANNEL: ${{ env.SLACK_CHANNEL }}
          AWS_REGION: eu-west-1
          AWS_DEPLOY_STAGE_ENVIRONMENT: ${{ env.BRANCH_NAME }}
          # scannerHome: SonarQubeScanner4.0
          # AWS_PROFILE: dev

      # - name: Fleet Indexing Script
      #   run: |
      #     sudo sh scripts/iot-fleet-indexing-config.sh
      #   env:
      #     AWS_REGION: ${{ env.AWS_REGION }}
      #     AWS_PROFILE: ${{ env.AWS_PROFILE }}

      # - name: SonarQube analysis
      #   run: |
      #     ${{ env.scannerHome }}/bin/sonar-scanner \
      #       -Dsonar.projectKey=platform-manual-services-${{ env.AWS_DEPLOY_STAGE_ENVIRONMENT }} \
      #       -Dsonar.sources=. \
      #       -Dsonar.host.url=http://sonarqube.tools.emea-iot.aws.fluidra.com:9000 \
      #       -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
      #       -Dsonar.working.directory=${{ github.workspace }}/sonar

      - name: Deploy
        run: |
          sls plugin install -n serverless-prune-plugin --stage ${{ env.AWS_DEPLOY_STAGE_ENVIRONMENT }}
          sls prune --stage ${{ env.AWS_DEPLOY_STAGE_ENVIRONMENT }} -n 50
          sls -v
          sls deploy --stage ${{ env.AWS_DEPLOY_STAGE_ENVIRONMENT }} --force

      - name: Send Notification to Slack (Success)
        if: success()
        uses: rtCamp/action-slack-notify@v2
        with:
          webhook_url: ${{ secrets.SLACK_WEBHOOK }}
          color: '#00FF00'
          status: 'Success'
          fields: 'repo,commit,author,action'
          title: "Deploy ${{ github.run_number }} for platform-manual-services SUCCESS"
          message: "Build ${{ github.run_number }} for platform-manual-services completed successfully. View Run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

      - name: Send Notification to Slack (Failure)
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        with:
          webhook_url: ${{ secrets.SLACK_WEBHOOK }}
          color: '#FF0000'
          status: 'Failure'
          fields: 'repo,commit,author,action'
          title: "Deploy ${{ github.run_number }} for platform-manual-services FAILED"
          message: "Build ${{ github.run_number }} for platform-manual-services failed. View Run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
